/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 15/07/2021 11:25:10
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            24000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     216000000
#define MX_HCLKFreq_Value                       216000000
#define MX_FCLKCortexFreq_Value                 216000000
#define MX_CortexFreq_Value                     216000000
#define MX_AHBFreq_Value                        216000000
#define MX_APB1Freq_Value                       54000000
#define MX_APB2Freq_Value                       108000000
#define MX_APB1TimFreq_Value                    108000000
#define MX_APB2TimFreq_Value                    216000000
#define MX_EthernetFreq_Value                   216000000
#define MX_CECFreq_Value                        32786
#define MX_I2C1Freq_Value                       54000000
#define MX_I2C2Freq_Value                       54000000
#define MX_I2C3Freq_Value                       54000000
#define MX_I2C4Freq_Value                       54000000
#define MX_I2SFreq_Value                        192000000
#define MX_SAI1Freq_Value                       192000000
#define MX_SAI2Freq_Value                       192000000
#define MX_SDMMCFreq_Value                      48000000
#define MX_RTCFreq_Value                        32000
#define MX_USART1Freq_Value                     108000000
#define MX_USART2Freq_Value                     54000000
#define MX_USART3Freq_Value                     54000000
#define MX_UART4Freq_Value                      54000000
#define MX_UART5Freq_Value                      54000000
#define MX_UART8Freq_Value                      54000000
#define MX_UART7Freq_Value                      54000000
#define MX_USART6Freq_Value                     108000000
#define MX_USBFreq_Value                        48000000
#define MX_WatchDogFreq_Value                   32000
#define MX_LPTIM1Freq_Value                     54000000
#define MX_SPDIFRXFreq_Value                    192000000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    216000000

/*-------------------------------- ADC1       --------------------------------*/

#define MX_ADC1                                 1

/* GPIO Configuration */

/* Pin PA4 */
#define MX_ADCx_IN4_Pin                         PA4
#define MX_ADCx_IN4_GPIOx                       GPIOA
#define MX_ADCx_IN4_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC_Bus_24V                          ADCx_IN4
#define MX_ADCx_IN4_GPIO_Pin                    GPIO_PIN_4
#define MX_ADCx_IN4_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PA5 */
#define MX_ADCx_IN5_Pin                         PA5
#define MX_ADCx_IN5_GPIOx                       GPIOA
#define MX_ADCx_IN5_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC_NTC_Admision                     ADCx_IN5
#define MX_ADCx_IN5_GPIO_Pin                    GPIO_PIN_5
#define MX_ADCx_IN5_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PA6 */
#define MX_ADCx_IN6_Pin                         PA6
#define MX_ADCx_IN6_GPIOx                       GPIOA
#define MX_ADCx_IN6_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC_NTC_LCL                          ADCx_IN6
#define MX_ADCx_IN6_GPIO_Pin                    GPIO_PIN_6
#define MX_ADCx_IN6_GPIO_Mode                   GPIO_MODE_ANALOG

/* DMA Configuration */

/* DMA ADC1 */
#define MX_ADC1_DMA_MemBurst                    DMA_MBURST_SINGLE
#define MX_ADC1_DMA_Instance                    DMA2_Stream4
#define MX_ADC1_DMA_FIFOMode                    DMA_FIFOMODE_ENABLE
#define MX_ADC1_DMA_Priority                    DMA_PRIORITY_LOW
#define MX_ADC1_DMA_Channel                     DMA_CHANNEL_0
#define MX_ADC1_DMA_MemDataAlignment            DMA_MDATAALIGN_HALFWORD
#define MX_ADC1_DMA_Mode                        DMA_CIRCULAR
#define MX_ADC1_DMA_Direction                   DMA_PERIPH_TO_MEMORY
#define MX_ADC1_DMA_PeriphBurst                 DMA_PBURST_SINGLE
#define MX_ADC1_DMA_MemInc                      DMA_MINC_ENABLE
#define MX_ADC1_DMA_IpInstance                  
#define MX_ADC1_DMA_DMA_Handle                  
#define MX_ADC1_DMA_PeriphDataAlignment         DMA_PDATAALIGN_HALFWORD
#define MX_ADC1_DMA_PeriphInc                   DMA_PINC_DISABLE
#define MX_ADC1_DMA_FIFOThreshold               DMA_FIFO_THRESHOLD_HALFFULL

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- CRC        --------------------------------*/

#define MX_CRC                                  1

/* GPIO Configuration */

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA2_Stream2_IRQn */
#define MX_DMA2_Stream2_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream2_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream2_IRQn_Subriority         0

/* NVIC DMA2_Stream4_IRQn */
#define MX_DMA2_Stream4_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream4_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream4_IRQn_Subriority         0

/* NVIC DMA2_Stream3_IRQn */
#define MX_DMA2_Stream3_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream3_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream3_IRQn_Subriority         0

/* NVIC DMA2_Stream0_IRQn */
#define MX_DMA2_Stream0_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream0_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream0_IRQn_Subriority         0

/* NVIC DMA2_Stream6_IRQn */
#define MX_DMA2_Stream6_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream6_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream6_IRQn_Subriority         0

/* NVIC DMA2_Stream1_IRQn */
#define MX_DMA2_Stream1_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream1_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream1_IRQn_Subriority         0

/* NVIC DMA2_Stream5_IRQn */
#define MX_DMA2_Stream5_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream5_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream5_IRQn_Subriority         0

/*-------------------------------- ETH        --------------------------------*/

#define MX_ETH                                  1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_ETH_REF_CLK_GPIO_Speed               GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_REF_CLK_Pin                      PA1
#define MX_ETH_REF_CLK_GPIOx                    GPIOA
#define MX_ETH_REF_CLK_GPIO_PuPd                GPIO_NOPULL
#define MX_MCU_ETH_RMII_REF_CLK                 ETH_REF_CLK
#define MX_ETH_REF_CLK_GPIO_Pin                 GPIO_PIN_1
#define MX_ETH_REF_CLK_GPIO_AF                  GPIO_AF11_ETH
#define MX_ETH_REF_CLK_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PA7 */
#define MX_ETH_CRS_DV_GPIO_Speed                GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_CRS_DV_Pin                       PA7
#define MX_ETH_CRS_DV_GPIOx                     GPIOA
#define MX_ETH_CRS_DV_GPIO_PuPd                 GPIO_NOPULL
#define MX_MCU_ETH_RMII_CRS_DV                  ETH_CRS_DV
#define MX_ETH_CRS_DV_GPIO_Pin                  GPIO_PIN_7
#define MX_ETH_CRS_DV_GPIO_AF                   GPIO_AF11_ETH
#define MX_ETH_CRS_DV_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PC4 */
#define MX_ETH_RXD0_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_RXD0_Pin                         PC4
#define MX_ETH_RXD0_GPIOx                       GPIOC
#define MX_ETH_RXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_MCU_ETH_RMII_RXD0                    ETH_RXD0
#define MX_ETH_RXD0_GPIO_Pin                    GPIO_PIN_4
#define MX_ETH_RXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD0_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC5 */
#define MX_ETH_RXD1_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_RXD1_Pin                         PC5
#define MX_ETH_RXD1_GPIOx                       GPIOC
#define MX_ETH_RXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_MCU_ETH_RMII_RXD1                    ETH_RXD1
#define MX_ETH_RXD1_GPIO_Pin                    GPIO_PIN_5
#define MX_ETH_RXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD1_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB11 */
#define MX_ETH_TX_EN_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_TX_EN_Pin                        PB11
#define MX_ETH_TX_EN_GPIOx                      GPIOB
#define MX_ETH_TX_EN_GPIO_PuPd                  GPIO_NOPULL
#define MX_ETH_RMII_TX_EN                       ETH_TX_EN
#define MX_ETH_TX_EN_GPIO_Pin                   GPIO_PIN_11
#define MX_ETH_TX_EN_GPIO_AF                    GPIO_AF11_ETH
#define MX_ETH_TX_EN_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA2 */
#define MX_ETH_MDIO_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_MDIO_Pin                         PA2
#define MX_ETH_MDIO_GPIOx                       GPIOA
#define MX_ETH_MDIO_GPIO_PuPd                   GPIO_NOPULL
#define MX_MCU_ETH_RMII_MDIO                    ETH_MDIO
#define MX_ETH_MDIO_GPIO_Pin                    GPIO_PIN_2
#define MX_ETH_MDIO_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_MDIO_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB13 */
#define MX_ETH_TXD1_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_TXD1_Pin                         PB13
#define MX_ETH_TXD1_GPIOx                       GPIOB
#define MX_ETH_TXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_MCU_ETH_RMII_TXD1                    ETH_TXD1
#define MX_ETH_TXD1_GPIO_Pin                    GPIO_PIN_13
#define MX_ETH_TXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD1_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB12 */
#define MX_ETH_TXD0_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_TXD0_Pin                         PB12
#define MX_ETH_TXD0_GPIOx                       GPIOB
#define MX_ETH_TXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_MCU_ETH_RMII_TXD0                    ETH_TXD0
#define MX_ETH_TXD0_GPIO_Pin                    GPIO_PIN_12
#define MX_ETH_TXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD0_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC1 */
#define MX_ETH_MDC_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_MDC_Pin                          PC1
#define MX_ETH_MDC_GPIOx                        GPIOC
#define MX_ETH_MDC_GPIO_PuPd                    GPIO_NOPULL
#define MX_MCU_ETH_RMII_MDC_                    ETH_MDC
#define MX_ETH_MDC_GPIO_Pin                     GPIO_PIN_1
#define MX_ETH_MDC_GPIO_AF                      GPIO_AF11_ETH
#define MX_ETH_MDC_GPIO_Mode                    GPIO_MODE_AF_PP

/*-------------------------------- I2C2       --------------------------------*/

#define MX_I2C2                                 1

/* GPIO Configuration */

/* Pin PF0 */
#define MX_I2C2_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C2_SDA_Pin                         PF0
#define MX_I2C2_SDA_GPIOx                       GPIOF
#define MX_I2C2_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_MCU_I2C_SDA                          I2C2_SDA
#define MX_I2C2_SDA_GPIO_Pin                    GPIO_PIN_0
#define MX_I2C2_SDA_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PF1 */
#define MX_I2C2_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C2_SCL_Pin                         PF1
#define MX_I2C2_SCL_GPIOx                       GPIOF
#define MX_I2C2_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_MCU_I2C_SCL                          I2C2_SCL
#define MX_I2C2_SCL_GPIO_Pin                    GPIO_PIN_1
#define MX_I2C2_SCL_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- IWDG       --------------------------------*/

#define MX_IWDG                                 1

/* GPIO Configuration */

/*-------------------------------- QUADSPI    --------------------------------*/

#define MX_QUADSPI                              1

/* GPIO Configuration */

/* Pin PB2 */
#define MX_QUADSPI_CLK_GPIO_Speed               GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_CLK_Pin                      PB2
#define MX_QUADSPI_CLK_GPIOx                    GPIOB
#define MX_QUADSPI_CLK_GPIO_PuPd                GPIO_NOPULL
#define MX_MCU_QSPI_CLK                         QUADSPI_CLK
#define MX_QUADSPI_CLK_GPIO_Pin                 GPIO_PIN_2
#define MX_QUADSPI_CLK_GPIO_AF                  GPIO_AF9_QUADSPI
#define MX_QUADSPI_CLK_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PB10 */
#define MX_QUADSPI_BK1_NCS_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_NCS_Pin                  PB10
#define MX_QUADSPI_BK1_NCS_GPIOx                GPIOB
#define MX_QUADSPI_BK1_NCS_GPIO_PuPd            GPIO_NOPULL
#define MX_MCU_QSPI_CS_FLASH                    QUADSPI_BK1_NCS
#define MX_QUADSPI_BK1_NCS_GPIO_Pin             GPIO_PIN_10
#define MX_QUADSPI_BK1_NCS_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_NCS_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PD13 */
#define MX_QUADSPI_BK1_IO3_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO3_Pin                  PD13
#define MX_QUADSPI_BK1_IO3_GPIOx                GPIOD
#define MX_QUADSPI_BK1_IO3_GPIO_PuPd            GPIO_NOPULL
#define MX_MCU_QSPI_DQ3                         QUADSPI_BK1_IO3
#define MX_QUADSPI_BK1_IO3_GPIO_Pin             GPIO_PIN_13
#define MX_QUADSPI_BK1_IO3_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_IO3_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PE2 */
#define MX_QUADSPI_BK1_IO2_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO2_Pin                  PE2
#define MX_QUADSPI_BK1_IO2_GPIOx                GPIOE
#define MX_QUADSPI_BK1_IO2_GPIO_PuPd            GPIO_NOPULL
#define MX_MCU_QSPI_DQ2                         QUADSPI_BK1_IO2
#define MX_QUADSPI_BK1_IO2_GPIO_Pin             GPIO_PIN_2
#define MX_QUADSPI_BK1_IO2_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_IO2_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PD12 */
#define MX_QUADSPI_BK1_IO1_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO1_Pin                  PD12
#define MX_QUADSPI_BK1_IO1_GPIOx                GPIOD
#define MX_QUADSPI_BK1_IO1_GPIO_PuPd            GPIO_NOPULL
#define MX_MCU_QSPI_DQ1                         QUADSPI_BK1_IO1
#define MX_QUADSPI_BK1_IO1_GPIO_Pin             GPIO_PIN_12
#define MX_QUADSPI_BK1_IO1_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_IO1_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PD11 */
#define MX_QUADSPI_BK1_IO0_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO0_Pin                  PD11
#define MX_QUADSPI_BK1_IO0_GPIOx                GPIOD
#define MX_QUADSPI_BK1_IO0_GPIO_PuPd            GPIO_NOPULL
#define MX_MCU_QSPI_DQ0                         QUADSPI_BK1_IO0
#define MX_QUADSPI_BK1_IO0_GPIO_Pin             GPIO_PIN_11
#define MX_QUADSPI_BK1_IO0_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_IO0_GPIO_Mode            GPIO_MODE_AF_PP

/*-------------------------------- RTC        --------------------------------*/

#define MX_RTC                                  1

/* GPIO Configuration */

/*-------------------------------- SDMMC1     --------------------------------*/

#define MX_SDMMC1                               1

/* GPIO Configuration */

/* Pin PC8 */
#define MX_SDMMC1_D0_Pin                        PC8
#define MX_SDMMC1_D0_GPIOx                      GPIOC
#define MX_SDMMC1_D0_GPIO_PuPd                  GPIO_PULLUP
#define MX_SDMMC1_D0_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_MCU_MicroSD_D0                       SDMMC1_D0
#define MX_SDMMC1_D0_GPIO_Pin                   GPIO_PIN_8
#define MX_SDMMC1_D0_GPIO_AF                    GPIO_AF12_SDMMC1
#define MX_SDMMC1_D0_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PD2 */
#define MX_SDMMC1_CMD_Pin                       PD2
#define MX_SDMMC1_CMD_GPIOx                     GPIOD
#define MX_SDMMC1_CMD_GPIO_PuPd                 GPIO_PULLUP
#define MX_SDMMC1_CMD_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_MCU_MicroSD_CMD                      SDMMC1_CMD
#define MX_SDMMC1_CMD_GPIO_Pin                  GPIO_PIN_2
#define MX_SDMMC1_CMD_GPIO_AF                   GPIO_AF12_SDMMC1
#define MX_SDMMC1_CMD_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PC9 */
#define MX_SDMMC1_D1_Pin                        PC9
#define MX_SDMMC1_D1_GPIOx                      GPIOC
#define MX_SDMMC1_D1_GPIO_PuPd                  GPIO_PULLUP
#define MX_SDMMC1_D1_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_MCU_MicroSD_D1                       SDMMC1_D1
#define MX_SDMMC1_D1_GPIO_Pin                   GPIO_PIN_9
#define MX_SDMMC1_D1_GPIO_AF                    GPIO_AF12_SDMMC1
#define MX_SDMMC1_D1_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC10 */
#define MX_SDMMC1_D2_Pin                        PC10
#define MX_SDMMC1_D2_GPIOx                      GPIOC
#define MX_SDMMC1_D2_GPIO_PuPd                  GPIO_PULLUP
#define MX_SDMMC1_D2_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_MCU_MicroSD_D2                       SDMMC1_D2
#define MX_SDMMC1_D2_GPIO_Pin                   GPIO_PIN_10
#define MX_SDMMC1_D2_GPIO_AF                    GPIO_AF12_SDMMC1
#define MX_SDMMC1_D2_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC11 */
#define MX_SDMMC1_D3_Pin                        PC11
#define MX_SDMMC1_D3_GPIOx                      GPIOC
#define MX_SDMMC1_D3_GPIO_PuPd                  GPIO_PULLUP
#define MX_SDMMC1_D3_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_MCU_MicroSD_D3                       SDMMC1_D3
#define MX_SDMMC1_D3_GPIO_Pin                   GPIO_PIN_11
#define MX_SDMMC1_D3_GPIO_AF                    GPIO_AF12_SDMMC1
#define MX_SDMMC1_D3_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC12 */
#define MX_SDMMC1_CK_Pin                        PC12
#define MX_SDMMC1_CK_GPIOx                      GPIOC
#define MX_SDMMC1_CK_GPIO_PuPd                  GPIO_NOPULL
#define MX_SDMMC1_CK_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_MCU_MicroSD_CLK                      SDMMC1_CK
#define MX_SDMMC1_CK_GPIO_Pin                   GPIO_PIN_12
#define MX_SDMMC1_CK_GPIO_AF                    GPIO_AF12_SDMMC1
#define MX_SDMMC1_CK_GPIO_Mode                  GPIO_MODE_AF_PP

/* DMA Configuration */

/* DMA SDMMC1_TX */
#define MX_SDMMC1_TX_DMA_MemBurst               DMA_MBURST_INC4
#define MX_SDMMC1_TX_DMA_Instance               DMA2_Stream3
#define MX_SDMMC1_TX_DMA_FIFOMode               DMA_FIFOMODE_ENABLE
#define MX_SDMMC1_TX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_SDMMC1_TX_DMA_Channel                DMA_CHANNEL_4
#define MX_SDMMC1_TX_DMA_MemDataAlignment       DMA_MDATAALIGN_WORD
#define MX_SDMMC1_TX_DMA_Mode                   DMA_PFCTRL
#define MX_SDMMC1_TX_DMA_Direction              DMA_MEMORY_TO_PERIPH
#define MX_SDMMC1_TX_DMA_PeriphBurst            DMA_PBURST_INC4
#define MX_SDMMC1_TX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_SDMMC1_TX_DMA_IpInstance             
#define MX_SDMMC1_TX_DMA_DMA_Handle             
#define MX_SDMMC1_TX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_WORD
#define MX_SDMMC1_TX_DMA_PeriphInc              DMA_PINC_DISABLE
#define MX_SDMMC1_TX_DMA_FIFOThreshold          DMA_FIFO_THRESHOLD_FULL

/* DMA SDMMC1_RX */
#define MX_SDMMC1_RX_DMA_MemBurst               DMA_MBURST_INC4
#define MX_SDMMC1_RX_DMA_Instance               DMA2_Stream6
#define MX_SDMMC1_RX_DMA_FIFOMode               DMA_FIFOMODE_ENABLE
#define MX_SDMMC1_RX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_SDMMC1_RX_DMA_Channel                DMA_CHANNEL_4
#define MX_SDMMC1_RX_DMA_MemDataAlignment       DMA_MDATAALIGN_WORD
#define MX_SDMMC1_RX_DMA_Mode                   DMA_PFCTRL
#define MX_SDMMC1_RX_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_SDMMC1_RX_DMA_PeriphBurst            DMA_PBURST_INC4
#define MX_SDMMC1_RX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_SDMMC1_RX_DMA_IpInstance             
#define MX_SDMMC1_RX_DMA_DMA_Handle             
#define MX_SDMMC1_RX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_WORD
#define MX_SDMMC1_RX_DMA_PeriphInc              DMA_PINC_DISABLE
#define MX_SDMMC1_RX_DMA_FIFOThreshold          DMA_FIFO_THRESHOLD_FULL

/* NVIC Configuration */

/* NVIC SDMMC1_IRQn */
#define MX_SDMMC1_IRQn_interruptPremptionPriority 0
#define MX_SDMMC1_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_SDMMC1_IRQn_Subriority               0

/*-------------------------------- SPI1       --------------------------------*/

#define MX_SPI1                                 1

/* GPIO Configuration */

/* Pin PD7 */
#define MX_SPI1_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_MOSI_Pin                        PD7
#define MX_SPI1_MOSI_GPIOx                      GPIOD
#define MX_SPI1_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_DSP_MCU_SPI_SIMO                     SPI1_MOSI
#define MX_SPI1_MOSI_GPIO_Pin                   GPIO_PIN_7
#define MX_SPI1_MOSI_GPIO_AF                    GPIO_AF5_SPI1
#define MX_SPI1_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PG9 */
#define MX_SPI1_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_MISO_Pin                        PG9
#define MX_SPI1_MISO_GPIOx                      GPIOG
#define MX_SPI1_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_DSP_MCU_SPI_SOMI                     SPI1_MISO
#define MX_SPI1_MISO_GPIO_Pin                   GPIO_PIN_9
#define MX_SPI1_MISO_GPIO_AF                    GPIO_AF5_SPI1
#define MX_SPI1_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PG11 */
#define MX_SPI1_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_SCK_Pin                         PG11
#define MX_SPI1_SCK_GPIOx                       GPIOG
#define MX_SPI1_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_DSP_MCU_SPI_CLK                      SPI1_SCK
#define MX_SPI1_SCK_GPIO_Pin                    GPIO_PIN_11
#define MX_SPI1_SCK_GPIO_AF                     GPIO_AF5_SPI1
#define MX_SPI1_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* DMA Configuration */

/* DMA SPI1_RX */
#define MX_SPI1_RX_DMA_DMA_Handle               
#define MX_SPI1_RX_DMA_Instance                 DMA2_Stream2
#define MX_SPI1_RX_DMA_FIFOMode                 DMA_FIFOMODE_DISABLE
#define MX_SPI1_RX_DMA_Priority                 DMA_PRIORITY_MEDIUM
#define MX_SPI1_RX_DMA_Channel                  DMA_CHANNEL_3
#define MX_SPI1_RX_DMA_PeriphDataAlignment      DMA_PDATAALIGN_HALFWORD
#define MX_SPI1_RX_DMA_MemDataAlignment         DMA_MDATAALIGN_HALFWORD
#define MX_SPI1_RX_DMA_Mode                     DMA_NORMAL
#define MX_SPI1_RX_DMA_Direction                DMA_PERIPH_TO_MEMORY
#define MX_SPI1_RX_DMA_PeriphInc                DMA_PINC_DISABLE
#define MX_SPI1_RX_DMA_MemInc                   DMA_MINC_ENABLE
#define MX_SPI1_RX_DMA_IpInstance               

/* DMA SPI1_TX */
#define MX_SPI1_TX_DMA_DMA_Handle               
#define MX_SPI1_TX_DMA_Instance                 DMA2_Stream5
#define MX_SPI1_TX_DMA_FIFOMode                 DMA_FIFOMODE_DISABLE
#define MX_SPI1_TX_DMA_Priority                 DMA_PRIORITY_MEDIUM
#define MX_SPI1_TX_DMA_Channel                  DMA_CHANNEL_3
#define MX_SPI1_TX_DMA_PeriphDataAlignment      DMA_PDATAALIGN_HALFWORD
#define MX_SPI1_TX_DMA_MemDataAlignment         DMA_MDATAALIGN_HALFWORD
#define MX_SPI1_TX_DMA_Mode                     DMA_NORMAL
#define MX_SPI1_TX_DMA_Direction                DMA_MEMORY_TO_PERIPH
#define MX_SPI1_TX_DMA_PeriphInc                DMA_PINC_DISABLE
#define MX_SPI1_TX_DMA_MemInc                   DMA_MINC_ENABLE
#define MX_SPI1_TX_DMA_IpInstance               

/*-------------------------------- SPI2       --------------------------------*/

#define MX_SPI2                                 1

/* GPIO Configuration */

/* Pin PI1 */
#define MX_SPI2_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_SCK_Pin                         PI1
#define MX_SPI2_SCK_GPIOx                       GPIOI
#define MX_SPI2_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_MCU_FRAM_SPI2_SCK                    SPI2_SCK
#define MX_SPI2_SCK_GPIO_Pin                    GPIO_PIN_1
#define MX_SPI2_SCK_GPIO_AF                     GPIO_AF5_SPI2
#define MX_SPI2_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PI0 */
#define MX_SPI2_NSS_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_NSS_Pin                         PI0
#define MX_SPI2_NSS_GPIOx                       GPIOI
#define MX_SPI2_NSS_GPIO_PuPd                   GPIO_NOPULL
#define MX_MCU_FRAM_SPI2_CSn                    SPI2_NSS
#define MX_SPI2_NSS_GPIO_Pin                    GPIO_PIN_0
#define MX_SPI2_NSS_GPIO_AF                     GPIO_AF5_SPI2
#define MX_SPI2_NSS_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PI2 */
#define MX_SPI2_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_MISO_Pin                        PI2
#define MX_SPI2_MISO_GPIOx                      GPIOI
#define MX_SPI2_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_MCU_FRAM_SPI2_MISO                   SPI2_MISO
#define MX_SPI2_MISO_GPIO_Pin                   GPIO_PIN_2
#define MX_SPI2_MISO_GPIO_AF                    GPIO_AF5_SPI2
#define MX_SPI2_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PI3 */
#define MX_SPI2_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_MOSI_Pin                        PI3
#define MX_SPI2_MOSI_GPIOx                      GPIOI
#define MX_SPI2_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_MCU_FRAM_SPI2_MOSI                   SPI2_MOSI
#define MX_SPI2_MOSI_GPIO_Pin                   GPIO_PIN_3
#define MX_SPI2_MOSI_GPIO_AF                    GPIO_AF5_SPI2
#define MX_SPI2_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- SPI4       --------------------------------*/

#define MX_SPI4                                 1

/* GPIO Configuration */

/* Pin PE13 */
#define MX_SPI4_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI4_MISO_Pin                        PE13
#define MX_SPI4_MISO_GPIOx                      GPIOE
#define MX_SPI4_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_DSP_CM_MCU_SPI4_MISO                 SPI4_MISO
#define MX_SPI4_MISO_GPIO_Pin                   GPIO_PIN_13
#define MX_SPI4_MISO_GPIO_AF                    GPIO_AF5_SPI4
#define MX_SPI4_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PE14 */
#define MX_SPI4_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI4_MOSI_Pin                        PE14
#define MX_SPI4_MOSI_GPIOx                      GPIOE
#define MX_SPI4_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_DSP_CM_MCU_SPI4_MOSI                 SPI4_MOSI
#define MX_SPI4_MOSI_GPIO_Pin                   GPIO_PIN_14
#define MX_SPI4_MOSI_GPIO_AF                    GPIO_AF5_SPI4
#define MX_SPI4_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PE12 */
#define MX_SPI4_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI4_SCK_Pin                         PE12
#define MX_SPI4_SCK_GPIOx                       GPIOE
#define MX_SPI4_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_DSP_CM_MCU_SPI4_CLK                  SPI4_SCK
#define MX_SPI4_SCK_GPIO_Pin                    GPIO_PIN_12
#define MX_SPI4_SCK_GPIO_AF                     GPIO_AF5_SPI4
#define MX_SPI4_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* DMA Configuration */

/* DMA SPI4_RX */
#define MX_SPI4_RX_DMA_DMA_Handle               
#define MX_SPI4_RX_DMA_Instance                 DMA2_Stream0
#define MX_SPI4_RX_DMA_FIFOMode                 DMA_FIFOMODE_DISABLE
#define MX_SPI4_RX_DMA_Priority                 DMA_PRIORITY_MEDIUM
#define MX_SPI4_RX_DMA_Channel                  DMA_CHANNEL_4
#define MX_SPI4_RX_DMA_PeriphDataAlignment      DMA_PDATAALIGN_HALFWORD
#define MX_SPI4_RX_DMA_MemDataAlignment         DMA_MDATAALIGN_HALFWORD
#define MX_SPI4_RX_DMA_Mode                     DMA_NORMAL
#define MX_SPI4_RX_DMA_Direction                DMA_PERIPH_TO_MEMORY
#define MX_SPI4_RX_DMA_PeriphInc                DMA_PINC_DISABLE
#define MX_SPI4_RX_DMA_MemInc                   DMA_MINC_ENABLE
#define MX_SPI4_RX_DMA_IpInstance               

/* DMA SPI4_TX */
#define MX_SPI4_TX_DMA_DMA_Handle               
#define MX_SPI4_TX_DMA_Instance                 DMA2_Stream1
#define MX_SPI4_TX_DMA_FIFOMode                 DMA_FIFOMODE_DISABLE
#define MX_SPI4_TX_DMA_Priority                 DMA_PRIORITY_MEDIUM
#define MX_SPI4_TX_DMA_Channel                  DMA_CHANNEL_4
#define MX_SPI4_TX_DMA_PeriphDataAlignment      DMA_PDATAALIGN_HALFWORD
#define MX_SPI4_TX_DMA_MemDataAlignment         DMA_MDATAALIGN_HALFWORD
#define MX_SPI4_TX_DMA_Mode                     DMA_NORMAL
#define MX_SPI4_TX_DMA_Direction                DMA_MEMORY_TO_PERIPH
#define MX_SPI4_TX_DMA_PeriphInc                DMA_PINC_DISABLE
#define MX_SPI4_TX_DMA_MemInc                   DMA_MINC_ENABLE
#define MX_SPI4_TX_DMA_IpInstance               

/*-------------------------------- SPI5       --------------------------------*/

#define MX_SPI5                                 1

/* GPIO Configuration */

/* Pin PF7 */
#define MX_SPI5_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI5_SCK_Pin                         PF7
#define MX_SPI5_SCK_GPIOx                       GPIOF
#define MX_SPI5_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_MCU_PT100_SPI5_CLK                   SPI5_SCK
#define MX_SPI5_SCK_GPIO_Pin                    GPIO_PIN_7
#define MX_SPI5_SCK_GPIO_AF                     GPIO_AF5_SPI5
#define MX_SPI5_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PF8 */
#define MX_SPI5_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI5_MISO_Pin                        PF8
#define MX_SPI5_MISO_GPIOx                      GPIOF
#define MX_SPI5_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_MCU_PT100_SPI5_MISO                  SPI5_MISO
#define MX_SPI5_MISO_GPIO_Pin                   GPIO_PIN_8
#define MX_SPI5_MISO_GPIO_AF                    GPIO_AF5_SPI5
#define MX_SPI5_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PF9 */
#define MX_SPI5_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI5_MOSI_Pin                        PF9
#define MX_SPI5_MOSI_GPIOx                      GPIOF
#define MX_SPI5_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_MCU_PT100_SPI5_MOSI                  SPI5_MOSI
#define MX_SPI5_MOSI_GPIO_Pin                   GPIO_PIN_9
#define MX_SPI5_MOSI_GPIO_AF                    GPIO_AF5_SPI5
#define MX_SPI5_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- SPI6       --------------------------------*/

#define MX_SPI6                                 1

/* GPIO Configuration */

/* Pin PG12 */
#define MX_SPI6_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI6_MISO_Pin                        PG12
#define MX_SPI6_MISO_GPIOx                      GPIOG
#define MX_SPI6_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_MCU_FRAM2_SPI6_MISO                  SPI6_MISO
#define MX_SPI6_MISO_GPIO_Pin                   GPIO_PIN_12
#define MX_SPI6_MISO_GPIO_AF                    GPIO_AF5_SPI6
#define MX_SPI6_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PG14 */
#define MX_SPI6_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI6_MOSI_Pin                        PG14
#define MX_SPI6_MOSI_GPIOx                      GPIOG
#define MX_SPI6_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_MCU_FRAM2_SPI6_MOSI                  SPI6_MOSI
#define MX_SPI6_MOSI_GPIO_Pin                   GPIO_PIN_14
#define MX_SPI6_MOSI_GPIO_AF                    GPIO_AF5_SPI6
#define MX_SPI6_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PG13 */
#define MX_SPI6_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI6_SCK_Pin                         PG13
#define MX_SPI6_SCK_GPIOx                       GPIOG
#define MX_SPI6_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_MCU_FRAM2_SPI6_CLK                   SPI6_SCK
#define MX_SPI6_SCK_GPIO_Pin                    GPIO_PIN_13
#define MX_SPI6_SCK_GPIO_AF                     GPIO_AF5_SPI6
#define MX_SPI6_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS_SWDIO_Pin                   PA13

/* Pin PA14 */
#define MX_SYS_JTCK_SWCLK_Pin                   PA14

/* Pin PA15 */
#define MX_SYS_JTDI_Pin                         PA15

/* Pin PB3 */
#define MX_SYS_JTDO_SWO_Pin                     PB3

/*-------------------------------- TIM6       --------------------------------*/

#define MX_TIM6                                 1

/* GPIO Configuration */

/*-------------------------------- TIM7       --------------------------------*/

#define MX_TIM7                                 1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM7_IRQn */
#define MX_TIM7_IRQn_interruptPremptionPriority 0
#define MX_TIM7_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_TIM7_IRQn_Subriority                 0

/*-------------------------------- UART7      --------------------------------*/

#define MX_UART7                                1

#define MX_UART7_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PE9 */
#define MX_UART7_DE_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART7_DE_Pin                         PE9
#define MX_UART7_DE_GPIOx                       GPIOE
#define MX_UART7_DE_GPIO_PuPd                   GPIO_NOPULL
#define MX_MCU_RS485_TXEN_ISO                   UART7_DE
#define MX_UART7_DE_GPIO_Pin                    GPIO_PIN_9
#define MX_UART7_DE_GPIO_AF                     GPIO_AF8_UART7
#define MX_UART7_DE_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PE8 */
#define MX_UART7_TX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART7_TX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART7_TX_Pin                         PE8
#define MX_UART7_TX_GPIOx                       GPIOE
#define MX_UART7_TX_GPIO_PuPd                   GPIO_NOPULL
#define MX_MCU_RS485_TX_ISO                     UART7_TX
#define MX_UART7_TX_GPIO_Pin                    GPIO_PIN_8
#define MX_UART7_TX_GPIO_AF                     GPIO_AF8_UART7

/* Pin PE7 */
#define MX_UART7_RX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART7_RX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART7_RX_Pin                         PE7
#define MX_UART7_RX_GPIOx                       GPIOE
#define MX_UART7_RX_GPIO_PuPd                   GPIO_NOPULL
#define MX_MCU_RS485_RX_ISO                     UART7_RX
#define MX_UART7_RX_GPIO_Pin                    GPIO_PIN_7
#define MX_UART7_RX_GPIO_AF                     GPIO_AF8_UART7

/*-------------------------------- UART8      --------------------------------*/

#define MX_UART8                                1

#define MX_UART8_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PD15 */
#define MX_UART8_DE_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART8_DE_Pin                         PD15
#define MX_UART8_DE_GPIOx                       GPIOD
#define MX_UART8_DE_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART8_DE                             UART8_DE
#define MX_UART8_DE_GPIO_Pin                    GPIO_PIN_15
#define MX_UART8_DE_GPIO_AF                     GPIO_AF8_UART8
#define MX_UART8_DE_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PE1 */
#define MX_UART8_TX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART8_TX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART8_TX_Pin                         PE1
#define MX_UART8_TX_GPIOx                       GPIOE
#define MX_UART8_TX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART8_TX                             UART8_TX
#define MX_UART8_TX_GPIO_Pin                    GPIO_PIN_1
#define MX_UART8_TX_GPIO_AF                     GPIO_AF8_UART8

/* Pin PE0 */
#define MX_UART8_RX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART8_RX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART8_RX_Pin                         PE0
#define MX_UART8_RX_GPIOx                       GPIOE
#define MX_UART8_RX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART8_RX                             UART8_RX
#define MX_UART8_RX_GPIO_Pin                    GPIO_PIN_0
#define MX_UART8_RX_GPIO_AF                     GPIO_AF8_UART8

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA9 */
#define MX_USART1_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_TX_Pin                        PA9
#define MX_USART1_TX_GPIOx                      GPIOA
#define MX_USART1_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_MCU_FPGA_USART1_TX                   USART1_TX
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_9
#define MX_USART1_TX_GPIO_AF                    GPIO_AF7_USART1

/* Pin PA10 */
#define MX_USART1_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_RX_Pin                        PA10
#define MX_USART1_RX_GPIOx                      GPIOA
#define MX_USART1_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_MCU_FPGA_USART1_RX                   USART1_RX
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_10
#define MX_USART1_RX_GPIO_AF                    GPIO_AF7_USART1

/*-------------------------------- USART2     --------------------------------*/

#define MX_USART2                               1

#define MX_USART2_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PD5 */
#define MX_USART2_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_TX_Pin                        PD5
#define MX_USART2_TX_GPIOx                      GPIOD
#define MX_USART2_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_MCU_FIBER_TX_ISOPRO                  USART2_TX
#define MX_USART2_TX_GPIO_Pin                   GPIO_PIN_5
#define MX_USART2_TX_GPIO_AF                    GPIO_AF7_USART2

/* Pin PD6 */
#define MX_USART2_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_RX_Pin                        PD6
#define MX_USART2_RX_GPIOx                      GPIOD
#define MX_USART2_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_MCU_FIBER_RX_ISOPRO                  USART2_RX
#define MX_USART2_RX_GPIO_Pin                   GPIO_PIN_6
#define MX_USART2_RX_GPIO_AF                    GPIO_AF7_USART2

/*-------------------------------- USART3     --------------------------------*/

#define MX_USART3                               1

#define MX_USART3_VM                            VM_ASYNC
#define MX_USART3_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PD8 */
#define MX_USART3_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART3_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART3_TX_Pin                        PD8
#define MX_USART3_TX_GPIOx                      GPIOD
#define MX_USART3_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_MCU_RS485_FAN_TX                     USART3_TX
#define MX_USART3_TX_GPIO_Pin                   GPIO_PIN_8
#define MX_USART3_TX_GPIO_AF                    GPIO_AF7_USART3

/* Pin PD9 */
#define MX_USART3_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART3_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART3_RX_Pin                        PD9
#define MX_USART3_RX_GPIOx                      GPIOD
#define MX_USART3_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_MCU_RS485_FAN_RX                     USART3_RX
#define MX_USART3_RX_GPIO_Pin                   GPIO_PIN_9
#define MX_USART3_RX_GPIO_AF                    GPIO_AF7_USART3

/* Pin PB14 */
#define MX_USART3_DE_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART3_DE_Pin                        PB14
#define MX_USART3_DE_GPIOx                      GPIOB
#define MX_USART3_DE_GPIO_PuPd                  GPIO_NOPULL
#define MX_MCU_RS485_FAN_TXEN                   USART3_DE
#define MX_USART3_DE_GPIO_Pin                   GPIO_PIN_14
#define MX_USART3_DE_GPIO_AF                    GPIO_AF7_USART3
#define MX_USART3_DE_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- USART6     --------------------------------*/

#define MX_USART6                               1

#define MX_USART6_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PC7 */
#define MX_USART6_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART6_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART6_RX_Pin                        PC7
#define MX_USART6_RX_GPIOx                      GPIOC
#define MX_USART6_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_DSP_MCU_SCIC_TX                      USART6_RX
#define MX_USART6_RX_GPIO_Pin                   GPIO_PIN_7
#define MX_USART6_RX_GPIO_AF                    GPIO_AF8_USART6

/* Pin PC6 */
#define MX_USART6_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART6_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART6_TX_Pin                        PC6
#define MX_USART6_TX_GPIOx                      GPIOC
#define MX_USART6_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_DSP_MCU_SCIC_RX                      USART6_TX
#define MX_USART6_TX_GPIO_Pin                   GPIO_PIN_6
#define MX_USART6_TX_GPIO_AF                    GPIO_AF8_USART6

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PH9 */
#define MX_PH9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH9_Pin                              PH9
#define MX_PH9_GPIOx                            GPIOH
#define MX_PH9_PinState                         GPIO_PIN_RESET
#define MX_PH9_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_ACT_AUX3                         PH9
#define MX_PH9_GPIO_Pin                         GPIO_PIN_9
#define MX_PH9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PH8 */
#define MX_PH8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH8_Pin                              PH8
#define MX_PH8_GPIOx                            GPIOH
#define MX_PH8_PinState                         GPIO_PIN_RESET
#define MX_PH8_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_ACT_LED_VERDE                    PH8
#define MX_PH8_GPIO_Pin                         GPIO_PIN_8
#define MX_PH8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB5 */
#define MX_PB5_Pin                              PB5
#define MX_PB5_GPIOx                            GPIOB
#define MX_PB5_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_CONFIG_2                         PB5
#define MX_PB5_GPIO_Pin                         GPIO_PIN_5
#define MX_PB5_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PB6 */
#define MX_PB6_Pin                              PB6
#define MX_PB6_GPIOx                            GPIOB
#define MX_PB6_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_IP_CONFIG                        PB6
#define MX_PB6_GPIO_Pin                         GPIO_PIN_6
#define MX_PB6_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PG0 */
#define MX_PG0_Pin                              PG0
#define MX_PG0_GPIOx                            GPIOG
#define MX_PG0_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_RETRO_CANAL_AC                   PG0
#define MX_PG0_GPIO_Pin                         GPIO_PIN_0
#define MX_PG0_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PG1 */
#define MX_PG1_Pin                              PG1
#define MX_PG1_GPIOx                            GPIOG
#define MX_PG1_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_RETRO_CANAL_ECON                 PG1
#define MX_PG1_GPIO_Pin                         GPIO_PIN_1
#define MX_PG1_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PI8 */
#define MX_PI8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PI8_Pin                              PI8
#define MX_PI8_GPIOx                            GPIOI
#define MX_PI8_PinState                         GPIO_PIN_RESET
#define MX_PI8_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_ACT_LED_FALLO                    PI8
#define MX_PI8_GPIO_Pin                         GPIO_PIN_8
#define MX_PI8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG8 */
#define MX_PG8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG8_Pin                              PG8
#define MX_PG8_GPIOx                            GPIOG
#define MX_PG8_PinState                         GPIO_PIN_RESET
#define MX_PG8_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_FRAM2_CS                         PG8
#define MX_PG8_GPIO_Pin                         GPIO_PIN_8
#define MX_PG8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PI9 */
#define MX_PI9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PI9_Pin                              PI9
#define MX_PI9_GPIOx                            GPIOI
#define MX_PI9_PinState                         GPIO_PIN_RESET
#define MX_PI9_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_ACT_FAN                          PI9
#define MX_PI9_GPIO_Pin                         GPIO_PIN_9
#define MX_PI9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC13 */
#define MX_PC13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PC13_Pin                             PC13
#define MX_PC13_GPIOx                           GPIOC
#define MX_PC13_PinState                        GPIO_PIN_RESET
#define MX_PC13_GPIO_PuPd                       GPIO_NOPULL
#define MX_MCU_ACT_FALLO                        PC13
#define MX_PC13_GPIO_Pin                        GPIO_PIN_13
#define MX_PC13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE11 */
#define MX_PE11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE11_Pin                             PE11
#define MX_PE11_GPIOx                           GPIOE
#define MX_PE11_PinState                        GPIO_PIN_RESET
#define MX_PE11_GPIO_PuPd                       GPIO_NOPULL
#define MX_SPI4_NSS                             PE11
#define MX_PE11_GPIO_Pin                        GPIO_PIN_11
#define MX_PE11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PF12 */
#define MX_PF12_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PF12_Pin                             PF12
#define MX_PF12_GPIOx                           GPIOF
#define MX_PF12_PinState                        GPIO_PIN_RESET
#define MX_PF12_GPIO_PuPd                       GPIO_NOPULL
#define MX_MCU_ACT_TRAFO_AUX                    PF12
#define MX_PF12_GPIO_Pin                        GPIO_PIN_12
#define MX_PF12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PH10 */
#define MX_PH10_Pin                             PH10
#define MX_PH10_GPIOx                           GPIOH
#define MX_PH10_GPIO_PuPd                       GPIO_NOPULL
#define MX_MCU_RETRO_TERM_TRAFO                 PH10
#define MX_PH10_GPIO_Pin                        GPIO_PIN_10
#define MX_PH10_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PG10 */
#define MX_PG10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PG10_Pin                             PG10
#define MX_PG10_GPIOx                           GPIOG
#define MX_PG10_PinState                        GPIO_PIN_RESET
#define MX_PG10_GPIO_PuPd                       GPIO_NOPULL
#define MX_SPI1_NSS                             PG10
#define MX_PG10_GPIO_Pin                        GPIO_PIN_10
#define MX_PG10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PH15 */
#define MX_PH15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PH15_Pin                             PH15
#define MX_PH15_GPIOx                           GPIOH
#define MX_PH15_PinState                        GPIO_PIN_RESET
#define MX_PH15_GPIO_PuPd                       GPIO_NOPULL
#define MX_MCU_ACT_AUX4                         PH15
#define MX_PH15_GPIO_Pin                        GPIO_PIN_15
#define MX_PH15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PH3 */
#define MX_PH3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH3_Pin                              PH3
#define MX_PH3_GPIOx                            GPIOH
#define MX_PH3_PinState                         GPIO_PIN_RESET
#define MX_PH3_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_ETH_RMII_RESET                   PH3
#define MX_PH3_GPIO_Pin                         GPIO_PIN_3
#define MX_PH3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PH2 */
#define MX_PH2_Pin                              PH2
#define MX_PH2_GPIOx                            GPIOH
#define MX_PH2_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_ETH_RMII_INT                     PH2
#define MX_PH2_GPIO_Pin                         GPIO_PIN_2
#define MX_PH2_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PI11 */
#define MX_PI11_Pin                             PI11
#define MX_PI11_GPIOx                           GPIOI
#define MX_PI11_GPIO_PuPd                       GPIO_NOPULL
#define MX_MCU_RETRO_AC_OVER                    PI11
#define MX_PI11_GPIO_Pin                        GPIO_PIN_11
#define MX_PI11_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PF3 */
#define MX_PF3_Pin                              PF3
#define MX_PF3_GPIOx                            GPIOF
#define MX_PF3_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_SETA1                            PF3
#define MX_PF3_GPIO_Pin                         GPIO_PIN_3
#define MX_PF3_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PH5 */
#define MX_PH5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH5_Pin                              PH5
#define MX_PH5_GPIOx                            GPIOH
#define MX_PH5_PinState                         GPIO_PIN_RESET
#define MX_PH5_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_LED_FAULT                        PH5
#define MX_PH5_GPIO_Pin                         GPIO_PIN_5
#define MX_PH5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PF14 */
#define MX_PF14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PF14_Pin                             PF14
#define MX_PF14_GPIOx                           GPIOF
#define MX_PF14_PinState                        GPIO_PIN_RESET
#define MX_PF14_GPIO_PuPd                       GPIO_NOPULL
#define MX_MCU_ACT_DCDC                         PF14
#define MX_PF14_GPIO_Pin                        GPIO_PIN_14
#define MX_PF14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PI10 */
#define MX_PI10_Pin                             PI10
#define MX_PI10_GPIOx                           GPIOI
#define MX_PI10_GPIO_PuPd                       GPIO_NOPULL
#define MX_MCU_RETRO_FAN                        PI10
#define MX_PI10_GPIO_Pin                        GPIO_PIN_10
#define MX_PI10_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PH4 */
#define MX_PH4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH4_Pin                              PH4
#define MX_PH4_GPIOx                            GPIOH
#define MX_PH4_PinState                         GPIO_PIN_RESET
#define MX_PH4_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_LED_LIFE                         PH4
#define MX_PH4_GPIO_Pin                         GPIO_PIN_4
#define MX_PH4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PF13 */
#define MX_PF13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PF13_Pin                             PF13
#define MX_PF13_GPIOx                           GPIOF
#define MX_PF13_PinState                        GPIO_PIN_RESET
#define MX_PF13_GPIO_PuPd                       GPIO_NOPULL
#define MX_MCU_ACT_ECON                         PF13
#define MX_PF13_GPIO_Pin                        GPIO_PIN_13
#define MX_PF13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PH11 */
#define MX_PH11_Pin                             PH11
#define MX_PH11_GPIOx                           GPIOH
#define MX_PH11_GPIO_PuPd                       GPIO_NOPULL
#define MX_MCU_RETRO_MUELLE                     PH11
#define MX_PH11_GPIO_Pin                        GPIO_PIN_11
#define MX_PH11_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PF5 */
#define MX_PF5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF5_Pin                              PF5
#define MX_PF5_GPIOx                            GPIOF
#define MX_PF5_PinState                         GPIO_PIN_RESET
#define MX_PF5_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_SPI5_DEV_SELECT                  PF5
#define MX_PF5_GPIO_Pin                         GPIO_PIN_5
#define MX_PF5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PH7 */
#define MX_PH7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH7_Pin                              PH7
#define MX_PH7_GPIOx                            GPIOH
#define MX_PH7_PinState                         GPIO_PIN_RESET
#define MX_PH7_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_ACT_AUX2                         PH7
#define MX_PH7_GPIO_Pin                         GPIO_PIN_7
#define MX_PH7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PH14 */
#define MX_PH14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PH14_Pin                             PH14
#define MX_PH14_GPIOx                           GPIOH
#define MX_PH14_PinState                        GPIO_PIN_RESET
#define MX_PH14_GPIO_PuPd                       GPIO_NOPULL
#define MX_MCU_CLOSE_DISY                       PH14
#define MX_PH14_GPIO_Pin                        GPIO_PIN_14
#define MX_PH14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PD3 */
#define MX_PD3_Pin                              PD3
#define MX_PD3_GPIOx                            GPIOD
#define MX_PD3_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_MicroSD_Detect                   PD3
#define MX_PD3_GPIO_Pin                         GPIO_PIN_3
#define MX_PD3_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PF4 */
#define MX_PF4_Pin                              PF4
#define MX_PF4_GPIOx                            GPIOF
#define MX_PF4_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_RETRO_ISOPRO                     PF4
#define MX_PF4_GPIO_Pin                         GPIO_PIN_4
#define MX_PF4_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PF15 */
#define MX_PF15_Pin                             PF15
#define MX_PF15_GPIOx                           GPIOF
#define MX_PF15_GPIO_PuPd                       GPIO_NOPULL
#define MX_MCU_RETRO_FALLO_DCDC                 PF15
#define MX_PF15_GPIO_Pin                        GPIO_PIN_15
#define MX_PF15_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PH6 */
#define MX_PH6_Pin                              PH6
#define MX_PH6_GPIOx                            GPIOH
#define MX_PH6_GPIO_PuPd                        GPIO_NOPULL
#define MX_MCU_RETRO_MARCHA                     PH6
#define MX_PH6_GPIO_Pin                         GPIO_PIN_6
#define MX_PH6_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PH13 */
#define MX_PH13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PH13_Pin                             PH13
#define MX_PH13_GPIOx                           GPIOH
#define MX_PH13_PinState                        GPIO_PIN_RESET
#define MX_PH13_GPIO_PuPd                       GPIO_NOPULL
#define MX_MCU_OPEN_DISY                        PH13
#define MX_PH13_GPIO_Pin                        GPIO_PIN_13
#define MX_PH13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

