# GDB script to load crash dump from 2025-07-24 20:33:51.209358
# Generated by STM32H7 Crash Dump Server

# Set architecture
set architecture armv7e-m
set arm fallback-mode thumb
set arm force-mode thumb

# Restore CPU registers
echo \n=== Restoring CPU registers ===\n
set $r0 = 0xFFFFFFFE
set $r1 = 0x00000004
set $r2 = 0xDEADBEEF
set $r3 = 0xFFFFFFFF
set $r4 = 0x00000000
set $r5 = 0x00000000
set $r6 = 0x00000000
set $r7 = 0x00000000
set $r8 = 0x00000000
set $r9 = 0x00000000
set $r10 = 0x00000000
set $r11 = 0x00000000
set $r12 = 0x0808B095
set $sp = 0x24015488
set $lr = 0x0804B0E1
set $pc = 0x08074DBE
set $xpsr = 0x610F0200

# Restore memory regions (may fail if memory is protected)
echo \n=== Restoring memory regions ===\n
echo Restoring AXI_SRAM...\n
restore dump_20250724_203351.bin binary 0x24000000 0x1bc 0x801bc

echo Restoring SRAM1...\n
restore dump_20250724_203351.bin binary 0x30000000 0x801bc 0xa01bc

echo Restoring SRAM2...\n
restore dump_20250724_203351.bin binary 0x30020000 0xa01bc 0xc01bc

echo Restoring SRAM3...\n
restore dump_20250724_203351.bin binary 0x30040000 0xc01bc 0xc81bc

echo Restoring SRAM4...\n
restore dump_20250724_203351.bin binary 0x38000000 0xc81bc 0xd81bc

echo Restoring BACKUP_SRAM...\n
restore dump_20250724_203351.bin binary 0x38800000 0xd81bc 0xd91bc

# Show restored state
echo \n=== State restored! ===\n
printf "PC = 0x%08x  ", $pc
x/i $pc
printf "LR = 0x%08x  ", $lr
x/i $lr
printf "SP = 0x%08x\n", $sp

echo \n=== CPU Registers ===\n
info registers

# Analyze the crash
if (analyze_crash)
  analyze_crash
else
  echo \nRun 'analyze_crash' to see crash analysis\n
end
