# GDB script to load crash dump from 2025-07-24 22:54:20.988429
# Generated by STM32H7 Crash Dump Server

# Set architecture
set architecture armv7e-m
set arm fallback-mode thumb
set arm force-mode thumb

# Restore CPU registers
echo \n=== Restoring CPU registers ===\n
set $r0 = 0x24000000
set $r1 = 0x24007180
set $r2 = 0x24006B0C
set $r3 = 0xFFDEFF35
set $r4 = 0x00000000
set $r5 = 0x00000000
set $r6 = 0x00000000
set $r7 = 0x00000000
set $r8 = 0x00000000
set $r9 = 0x00000000
set $r10 = 0x00000000
set $r11 = 0x00000000
set $r12 = 0x00000004
set $sp = 0x2001FF98
set $lr = 0x0808999D
set $pc = 0x0808A1EE
set $xpsr = 0xA100000F
set $msp = 0x2001FF98
set $psp = 0x00000000
set $control = 0x00000000
set $basepri = 0x00000000
set $primask = 0x00000000
set $faultmask = 0x00000000
set $fpscr = 0x00000000

# Enable all STM32H7 power domains first
echo Enabling STM32H7 power domains...\n
echo Enabling SRAM1/2/3 clocks (RCC AHB2ENR)...\n
set *(unsigned int*)0x580244DC = *(unsigned int*)0x580244DC | 0xE0000000
echo Enabling SRAM4 and Backup SRAM clocks (RCC AHB4ENR)...\n
set *(unsigned int*)0x580244E0 = *(unsigned int*)0x580244E0 | 0x10000000
echo Enabling backup domain access (PWR CR1)...\n
set *(unsigned int*)0x58024800 = *(unsigned int*)0x58024800 | 0x00000100

# Restore memory regions (may fail if target memory is protected)
echo \n=== Restoring memory regions ===\n
echo Restoring AXI_SRAM...\n
restore dump_20250724_225420.bin binary 0x23fffe44 0x1bc 0x801bc

echo Restoring SRAM1...\n
restore dump_20250724_225420.bin binary 0x2ff7fe44 0x801bc 0xa01bc

echo Restoring SRAM2...\n
restore dump_20250724_225420.bin binary 0x2ff7fe44 0xa01bc 0xc01bc

echo Restoring SRAM3...\n
restore dump_20250724_225420.bin binary 0x2ff7fe44 0xc01bc 0xc81bc

echo Restoring SRAM4...\n
restore dump_20250724_225420.bin binary 0x37f37e44 0xc81bc 0xd81bc

echo Restoring BACKUP_SRAM...\n
restore dump_20250724_225420.bin binary 0x38727e44 0xd81bc 0xd91bc

# Show restored state
echo \n=== State restored! ===\n
printf "PC = 0x%08x  ", $pc
x/i $pc
printf "LR = 0x%08x  ", $lr
x/i $lr
printf "SP = 0x%08x\n", $sp

echo \n=== CPU Registers ===\n
info registers

# Show backtrace
echo \n=== Backtrace ===\n
bt

# Show code around crash location
echo \n=== Code at crash location ===\n
list *$pc

# Update IDE view to show crash location
# Show all threads (OpenOCD RTOS support will handle this)
echo \n=== All Threads ===\n
info threads

# Show COMPLETE backtrace for ALL threads
echo \n=== Complete Thread Backtraces ===\n
thread apply all bt

# Select thread that crashed and position there
thread 1
frame 0
# Check fault registers
echo \n=== Fault Status Registers ===\n
set $cfsr = *(unsigned int*)0xE000ED28
set $hfsr = *(unsigned int*)0xE000ED2C
printf "CFSR = 0x%08x\n", $cfsr
printf "HFSR = 0x%08x\n", $hfsr

# Decode fault cause
if ($hfsr & 0x40000000)
  echo - FORCED: Hard fault escalated from another fault\n
end
if ($cfsr & 0x00008000)
  printf "- BFAR valid: 0x%08x\n", *(unsigned int*)0xE000ED38
end
if ($cfsr & 0x00000080)
  printf "- MMFAR valid: 0x%08x\n", *(unsigned int*)0xE000ED34
end

# Position at crash location
echo \n=== Positioning at crash location ===\n
# Refresh debugger views
info threads
info locals
info args
thread 1
# This forces IDEs to update their view
stepi 0

echo \n=== Crash dump loaded successfully! ===\n
echo You are now at the exact point of the crash.\n
echo Use 'bt' for backtrace, 'info locals' for variables.\n
